language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
  - pip install -U pip setuptools wheel
  - sudo apt-get -qq update 
  #- sudo apt-get install -y latexmk # out-of-date versions
  #- sudo apt-get install -y pandoc # out-of-date versions
  - sudo apt-get install -y texlive
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb

install:
    - travis_wait pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install .
    - pip install --quiet coverage
    - pip install --quiet coveralls

script:
    - nosetests -v --nocapture --with-doctest --with-coverage --exe --cover-package=ipypublish

after_success:
    - coveralls