language: python

matrix:
 include:
    - os: linux
      sudo: required
      python: 2.7
      dist: trusty # required for lates versions of pandoc and latexmk
      env: ALLOW_FAILURE=false
    - os: linux
      sudo: required
      python: 3.6
      dist: trusty
      env: ALLOW_FAILURE=false
    - os: osx
      language: generic
      env: ALLOW_FAILURE=false
      before_install:
        - travis_wait brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - brew install pandoc
        - brew upgrade wget
        - sudo wget http://mirror.ctan.org/systems/mac/mactex/BasicTeX.pkg -O BasicTeX.pkg
        - sudo installer -pkg BasicTeX.pkg -target /
        - export PATH=$PATH:/usr/texbin:/Library/TeX/texbin
        - sudo tlmgr update --self
        - sudo tlmgr install latexmk
        - sudo tlmgr install adjustbox
        - sudo tlmgr install collectbox
        - sudo tlmgr install ucs
        - sudo tlmgr install enumitem
        - sudo tlmgr install placeins
        - sudo tlmgr install todonotes
        - sudo tlmgr install chngcntr
        - sudo tlmgr install doi
        - sudo tlmgr install mdframed
        - sudo tlmgr install cleveref
        - sudo tlmgr install biblatex
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y pandoc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y texlive ; fi
  # required for some styles like adjustbox 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y texlive-latex-extra ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y latexmk ; fi

  - pip install -U pip setuptools wheel  

install:
    - travis_wait pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install .
    - pip install --quiet coverage
    - pip install --quiet coveralls

script:
    - nosetests -v --nocapture --with-doctest --with-coverage --exe --cover-package=ipypublish

after_success:
    - coveralls